# Generated by Django 3.0.3 on 2020-02-24 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('PJM', 'Project Manager'), ('CUS', 'Customer Interface'), ('BUS', 'Business Case Accountable'), ('LOG', 'Logistics Accountable'), ('PRO', 'Production Accountable'), ('QUA', 'Quality Accoutable'), ('GEN', 'General Manager'), ('PUR', 'Purchasing Accountable'), ('ACC', 'Accounting')], default='goods', max_length=3)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
