# Generated by Django 3.0.3 on 2020-02-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('PJM', 'Project Manager'), ('CUS', 'Customer Interface'), ('BUS', 'Business Case Accountable'), ('LOG', 'Logistics Accountable'), ('PRO', 'Production Accountable'), ('QUA', 'Quality Accoutable'), ('GEN', 'General Manager'), ('PUR', 'Purchasing Accountable'), ('ACC', 'Accounting'), ('LAW', 'Lawyer')], default='goods', max_length=3),
        ),
    ]
