# Generated by Django 3.0.3 on 2020-02-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_appendix1',
            field=models.FileField(default='', upload_to='contracts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_appendix2',
            field=models.FileField(default='', upload_to='contracts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(default='', upload_to='contracts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_file_signed',
            field=models.FileField(default='', upload_to='contracts/signed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_specification',
            field=models.FileField(default='', upload_to='contracts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('service', 'Service'), ('goods', 'Goods')], default='goods', max_length=7),
        ),
    ]
