# Generated by Django 3.0.3 on 2020-02-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_contract_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_currency',
            field=models.CharField(choices=[('RUR', 'Russian Ruble'), ('EUR', 'Euro'), ('USD', 'USA Dollar')], default='RUR', max_length=3),
        ),
    ]
